export const videos = [
  {
    id: 1,
    titulo: 'Lo mejor de la clasificación 6hs de Spa',
    linkVideo:
      'https://www.youtube.com/watch?v=2lOhk3DOK8s&ab_channel=FIAWorldEnduranceChampionship',
    linkImage: 'https://img.youtube.com/vi/2lOhk3DOK8s/maxresdefault.jpg',
    categoria: 'WEC',
    descripcion: 'Lo mejor de la clasificación del WEC en Spa-Francorchamps',
    codigoSeguridad: 'wechqspa2023',
  },
  {
    id: 2,
    titulo: 'Una vuelta con Giovinazzi en Spa',
    linkVideo:
      'https://www.youtube.com/watch?v=IrBYjeGdnI4&ab_channel=FIAWorldEnduranceChampionship',
    linkImage: 'https://img.youtube.com/vi/IrBYjeGdnI4/maxresdefault.jpg',
    categoria: 'WEC',
    descripcion: 'Abordo con la Ferrari #51 por el circuito de Spa-Francorchamps',
    codigoSeguridad: 'wecolspa2023',
  },
  {
    id: 3,
    titulo: 'FP1: La primera entrada en pista en Spa',
    linkVideo:
      'https://www.youtube.com/watch?v=XXdqVeMfJck&ab_channel=FIAWorldEnduranceChampionship',
    linkImage: 'https://img.youtube.com/vi/XXdqVeMfJck/maxresdefault.jpg',
    categoria: 'WEC',
    descripcion: 'Toda la acción en pista de las primeras prácticas del WEC en Spa-Francorchamps',
    codigoSeguridad: 'wecfp1spa2023',
  },
  {
    id: 4,
    titulo: 'FP2: Metiendo las mejores vueltas',
    linkVideo:
      'https://www.youtube.com/watch?v=4vvg39ONLrE&ab_channel=FIAWorldEnduranceChampionship',
    linkImage: 'https://img.youtube.com/vi/4vvg39ONLrE/maxresdefault.jpg',
    categoria: 'WEC',
    descripcion: 'Las mejores vueltas de una segunda práctica muy entretenida',
    codigoSeguridad: 'wecfp2spa2023',
  },
  {
    id: 5,
    titulo: 'FP3: Lluvia y seco en la última práctica',
    linkVideo:
      'https://www.youtube.com/watch?v=M_AyDeiqhlA&ab_channel=FIAWorldEnduranceChampionship',
    linkImage: 'https://img.youtube.com/vi/M_AyDeiqhlA/maxresdefault.jpg',
    categoria: 'WEC',
    descripcion: 'Las mejores vueltas de una tercera práctica muy cambiante',
    codigoSeguridad: 'wecfp3spa2023',
  },
  {
    id: 6,
    titulo: 'Lo mejor de las 3hs de Monza',
    linkVideo: 'https://www.youtube.com/watch?v=jieCtWmEykw&ab_channel=GTWorld',
    linkImage: 'https://img.youtube.com/vi/jieCtWmEykw/maxresdefault.jpg',
    categoria: 'GT',
    descripcion: 'Lo mejor de la primera fecha de la GT World Challenge Europe Endurance en Monza',
    codigoSeguridad: 'gtwchmonza2023',
  },
  {
    id: 7,
    titulo: 'Lo mejor de la Carrera 1 en Outlon Park',
    linkVideo: 'https://www.youtube.com/watch?v=bICfheCI0Fk&ab_channel=GTWorld',
    linkImage: 'https://img.youtube.com/vi/bICfheCI0Fk/maxresdefault.jpg',
    categoria: 'GT',
    descripcion:
      'Resumen con los mejores momentos de la primera carrera de la British GT en Outlon Park',
    codigoSeguridad: 'gtbr1outlonpark2023',
  },
  {
    id: 8,
    titulo: 'Lo mejor de la Carrera 2 en Outlon Park',
    linkVideo: 'https://www.youtube.com/watch?v=3HgniNHfID0&ab_channel=GTWorld',
    linkImage: 'https://img.youtube.com/vi/3HgniNHfID0/maxresdefault.jpg',
    categoria: 'GT',
    descripcion:
      'Resumen con los mejores momentos de la segunda carrera de la British GT en Outlon Park',
    codigoSeguridad: 'gtbr2outlonpark2023',
  },
  {
    id: 9,
    titulo: 'Rompiendo records en Outlon Park',
    linkVideo: 'https://www.youtube.com/watch?v=SjrGGi7_Mas&ab_channel=GTWorld',
    linkImage: 'https://img.youtube.com/vi/SjrGGi7_Mas/maxresdefault.jpg',
    categoria: 'GT',
    descripcion: 'La vuelta más rápida de la historia de la British GT en Outlon Park',
    codigoSeguridad: 'gtbrvroutlonpark2023',
  },
  {
    id: 10,
    titulo: 'Imágenes de la GT World Challenge America en Sonoma',
    linkVideo: 'https://www.youtube.com/watch?v=TA2vbek1CJU&ab_channel=GTWorld',
    linkImage: 'https://img.youtube.com/vi/TA2vbek1CJU/maxresdefault.jpg',
    categoria: 'GT',
    descripcion: 'Las mejores imágenes de la GT World Challenge America en Sonoma',
    codigoSeguridad: 'gtwamsonoma2023',
  },
  {
    id: 11,
    titulo: 'IndyCar: Resumen del Grand Prix of Long Beach',
    linkVideo: 'https://www.youtube.com/watch?v=g8k23jBQapM&t=239s&ab_channel=MotorsportsonNBC',
    linkImage: 'https://img.youtube.com/vi/g8k23jBQapM/maxresdefault.jpg',
    categoria: 'IndyCar',
    descripcion: 'Resumen con todo lo que dejó el GP de Long Beach de la IndyCar',
    codigoSeguridad: 'indycarlongbeach2023',
  },
  {
    id: 12,
    titulo: 'Top 10 de adelantamientos en Long Beach',
    linkVideo: 'https://www.youtube.com/watch?v=4OSi8zlexKM&ab_channel=NTTINDYCARSERIES',
    linkImage: 'https://img.youtube.com/vi/4OSi8zlexKM/maxresdefault.jpg',
    categoria: 'IndyCar',
    descripcion: 'Ranking de los mejores 10 adelantamientos del GP de Long Beach de la IndyCar',
    codigoSeguridad: 'indycarlbovertakes2023',
  },
  {
    id: 13,
    titulo: 'IndyCar: Resumen de la clasificación del Grand Prix of Long Beach',
    linkVideo: 'https://www.youtube.com/watch?v=HVsh8ZadL-s&ab_channel=NTTINDYCARSERIES',
    linkImage: 'https://img.youtube.com/vi/HVsh8ZadL-s/maxresdefault.jpg',
    categoria: 'IndyCar',
    descripcion: 'Los mejores momentos de la clasifiación del GP de Long Beach de la IndyCar',
    codigoSeguridad: 'indycarqualylb2023',
  },
  {
    id: 14,
    titulo: 'IndyCar: Resumen de la práctica 1 en Alabama',
    linkVideo: 'https://www.youtube.com/watch?v=hPpfS1kjHMw&ab_channel=NTTINDYCARSERIES',
    linkImage: 'https://img.youtube.com/vi/hPpfS1kjHMw/maxresdefault.jpg',
    categoria: 'IndyCar',
    descripcion: 'Los mejores momentos de la práctica 1 del GP de Alabama de la IndyCar',
    codigoSeguridad: 'indycarp1alabama2023',
  },
  {
    id: 15,
    titulo: 'Camino a Indy500: Cuando AJ Foyt ganó la edición de 1967',
    linkVideo: 'https://www.youtube.com/watch?v=biADfhgKe2g&ab_channel=MotorsportsonNBC',
    linkImage: 'https://img.youtube.com/vi/biADfhgKe2g/maxresdefault.jpg',
    categoria: 'IndyCar',
    descripcion: 'Un repaso de la victoria de AJ Foyt en las 500 Millas de Indianápolis de 1967',
    codigoSeguridad: 'indycarhindy5002023',
  },
]

export const categorias = [
  {
    id: 'fiawec',
    nombre: 'WEC',
    descripcion: 'Campeonato Mundial de Resistencia',
    color: '#005792',
    codigoSeguridad: 'fiawec2023',
  },
  {
    id: 'gt',
    nombre: 'GT',
    descripcion: 'GT World Challenge',
    color: '#00C86F',
    codigoSeguridad: 'gtwordlchallenge2023',
  },
  {
    id: 'indycar',
    nombre: 'IndyCar',
    descripcion: 'Todo lo relacionado a la IndyCar',
    color: '#6B5BE2',
    codigoSeguridad: 'indycar2023',
  },
]
